### ISSUE TITLE
NPE replacing tool part

### ISSUE THREAD

**Issue by Daenyth** [bonii-xx/IguanaTweaksTConstruct#21]
I was trying to replace a wood rod/copper bind/copper head + creeper head pickaxe with an iron head.

```
---- Minecraft Crash Report ----
// My bad.

Time: 8/29/14 10:49 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at iguanaman.iguanatweakstconstruct.replacing.ReplacementLogic.exchangeToolPart(ReplacementLogic.java:71)
    at iguanaman.iguanatweakstconstruct.replacing.ModPartReplacement.modify(ModPartReplacement.java:157)
    at tconstruct.library.crafting.ModifyBuilder.modifyItem(ModifyBuilder.java:31)
    at tconstruct.tools.logic.ToolStationLogic.buildTool(ToolStationLogic.java:83)
    at tconstruct.tools.logic.ToolStationLogic.func_70296_d(ToolStationLogic.java:64)
    at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:244)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:534)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:636)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:464)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:605)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at iguanaman.iguanatweakstconstruct.replacing.ReplacementLogic.exchangeToolPart(ReplacementLogic.java:71)
    at iguanaman.iguanatweakstconstruct.replacing.ModPartReplacement.modify(ModPartReplacement.java:157)
    at tconstruct.library.crafting.ModifyBuilder.modifyItem(ModifyBuilder.java:31)
    at tconstruct.tools.logic.ToolStationLogic.buildTool(ToolStationLogic.java:83)
    at tconstruct.tools.logic.ToolStationLogic.func_70296_d(ToolStationLogic.java:64)
    at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:244)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:534)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:636)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:464)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:605)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: iguanaman.iguanatweakstconstruct.harvestlevels.gui.ToolStationGUI

-- Affected level --
Details:
    Level name: MpServer
    All players: 2 total; [EntityClientPlayerMP['Daenyth'/210798, l='MpServer', x=397.72, y=66.62, z=422.42], EntityOtherPlayerMP['LilAlbatross'/225101, l='MpServer', x=397.41, y=64.00, z=424.88]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (344,64,302), Chunk: (at 8,4,14 in 21,18; contains blocks 336,0,288 to 351,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 3094455 game time, 3204899 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 78 total; [EntityEnderman['Enderman'/250002, l='MpServer', x=401.78, y=34.00, z=463.50], EntitySkeleton['Skeleton'/250015, l='MpServer', x=373.56, y=22.00, z=459.16], EntityCreeper['Creeper'/251331, l='MpServer', x=357.50, y=63.00, z=430.50], EntitySkeleton['Skeleton'/251094, l='MpServer', x=356.16, y=46.00, z=392.50], EntityBat['Bat'/251635, l='MpServer', x=329.50, y=29.21, z=350.57], EntityBat['Bat'/250802, l='MpServer', x=408.59, y=34.48, z=471.34], EntityOtherPlayerMP['LilAlbatross'/225101, l='MpServer', x=393.41, y=64.00, z=424.66], EntityBat['Bat'/251075, l='MpServer', x=447.98, y=39.24, z=392.97], EntityCreeper['Creeper'/249998, l='MpServer', x=406.50, y=33.00, z=473.50], EntityBat['Bat'/251073, l='MpServer', x=437.22, y=40.25, z=407.50], EntityBat['Bat'/251077, l='MpServer', x=449.31, y=37.95, z=387.66], EntityBat['Bat'/251076, l='MpServer', x=447.59, y=39.90, z=391.63], EntityCreeper['Creeper'/248363, l='MpServer', x=450.50, y=21.00, z=473.50], EntityZombie['Zombie'/607610, l='MpServer', x=44.04, y=-0.06, z=41.60], EntityOtherPlayerMP['LilAlbatross'/225101, l='MpServer', x=397.41, y=64.00, z=424.88], EntitySquid['Squid'/210284, l='MpServer', x=397.47, y=60.00, z=430.95], EntityBat['Bat'/251071, l='MpServer', x=437.53, y=41.79, z=406.25], EntitySquid['Squid'/210283, l='MpServer', x=398.38, y=60.47, z=429.47], EntityClientPlayerMP['Daenyth'/210798, l='MpServer', x=359.70, y=4.82, z=434.70], EntityCreeper['Creeper'/251303, l='MpServer', x=421.50, y=32.00, z=461.50], EntityCreeper['Creeper'/251302, l='MpServer', x=421.50, y=32.00, z=459.50], EntitySkeleton['Skeleton'/249114, l='MpServer', x=339.50, y=28.00, z=369.50], EntityOtherPlayerMP['LilAlbatross'/159686, l='MpServer', x=381.34, y=67.00, z=419.50], EntitySheep['Sheep'/160411, l='MpServer', x=384.41, y=74.00, z=497.88], EntitySquid['Squid'/213738, l='MpServer', x=396.06, y=60.02, z=430.51], EntitySquid['Squid'/213739, l='MpServer', x=397.25, y=60.32, z=430.50], EntityCreeper['Creeper'/248676, l='MpServer', x=321.50, y=30.00, z=497.50], EntityCreeper['Creeper'/251200, l='MpServer', x=316.50, y=41.00, z=387.50], EntitySkeleton['Skeleton'/250970, l='MpServer', x=349.50, y=20.00, z=473.50], EntitySkeleton['Skeleton'/250969, l='MpServer', x=352.50, y=20.00, z=473.50], EntitySheep['Sheep'/131, l='MpServer', x=319.66, y=70.00, z=403.44], EntityCreeper['Creeper'/250143, l='MpServer', x=362.50, y=19.00, z=458.50], EntitySquid['Squid'/238551, l='MpServer', x=400.53, y=59.89, z=430.27], EntitySheep['Sheep'/157, l='MpServer', x=400.69, y=65.00, z=374.91], EntitySheep['Sheep'/158, l='MpServer', x=384.19, y=66.00, z=376.13], EntitySheep['Sheep'/159, l='MpServer', x=363.94, y=64.00, z=387.91], EntitySquid['Squid'/203564, l='MpServer', x=399.46, y=60.30, z=429.60], EntitySquid['Squid'/238552, l='MpServer', x=395.47, y=59.44, z=430.47], EntityBat['Bat'/250404, l='MpServer', x=333.47, y=47.26, z=351.56], EntityZombie['Zombie'/250128, l='MpServer', x=395.44, y=39.00, z=460.13], EntityCreeper['Creeper'/250146, l='MpServer', x=361.50, y=19.00, z=458.50], EntityBat['Bat'/250629, l='MpServer', x=451.63, y=15.14, z=472.31], EntityCreeper['Creeper'/250147, l='MpServer', x=362.50, y=19.00, z=459.50], EntitySkeleton['Skeleton'/249906, l='MpServer', x=381.50, y=20.00, z=482.50], EntitySheep['Sheep'/186, l='MpServer', x=395.50, y=67.00, z=381.34], EntityCreeper['Creeper'/249896, l='MpServer', x=320.50, y=40.00, z=379.50], EntityCreeper['Creeper'/249897, l='MpServer', x=318.50, y=40.00, z=383.50], EntitySkeleton['Skeleton'/251468, l='MpServer', x=447.65, y=39.30, z=391.95], EntitySkeleton['Skeleton'/250986, l='MpServer', x=426.28, y=33.00, z=467.25], EntitySheep['Sheep'/182, l='MpServer', x=401.50, y=67.00, z=379.66], EntitySkeleton['Skeleton'/251467, l='MpServer', x=449.50, y=39.00, z=392.50], EntityCreeper['Creeper'/250991, l='MpServer', x=445.50, y=26.00, z=445.50], EntitySheep['Sheep'/181, l='MpServer', x=439.50, y=73.00, z=387.34], EntitySheep['Sheep'/205, l='MpServer', x=461.50, y=65.00, z=419.50], EntitySheep['Sheep'/204, l='MpServer', x=468.84, y=65.00, z=415.66], EntitySheep['Sheep'/206, l='MpServer', x=459.94, y=65.00, z=422.16], EntityCreeper['Creeper'/250488, l='MpServer', x=413.50, y=30.00, z=482.50], EntityCreeper['Creeper'/247559, l='MpServer', x=401.03, y=38.00, z=470.44], EntitySheep['Sheep'/203, l='MpServer', x=461.97, y=66.00, z=411.03], EntityCreeper['Creeper'/250490, l='MpServer', x=413.50, y=30.00, z=481.50], EntityBat['Bat'/250176, l='MpServer', x=346.40, y=55.65, z=349.05], EntitySheep['Sheep'/159691, l='MpServer', x=337.16, y=71.00, z=446.66], EntitySkeleton['Skeleton'/251695, l='MpServer', x=474.50, y=59.00, z=398.50], EntitySheep['Sheep'/159690, l='MpServer', x=351.09, y=70.00, z=435.06], EntitySheep['Sheep'/159689, l='MpServer', x=340.47, y=71.00, z=441.53], EntityCreeper['Creeper'/251697, l='MpServer', x=476.50, y=59.00, z=406.50], EntityZombie['Zombie'/251163, l='MpServer', x=440.50, y=26.00, z=492.50], EntitySheep['Sheep'/159714, l='MpServer', x=345.19, y=72.00, z=456.56], EntityCreeper['Creeper'/251394, l='MpServer', x=355.50, y=31.00, z=371.50], EntityCreeper['Creeper'/250717, l='MpServer', x=343.50, y=59.00, z=423.50], EntityCreeper['Creeper'/251395, l='MpServer', x=356.50, y=31.00, z=370.50], EntityCreeper['Creeper'/250716, l='MpServer', x=344.50, y=59.00, z=423.50], EntityEnderman['Enderman'/251393, l='MpServer', x=356.07, y=31.00, z=380.86], EntityClientPlayerMP['Daenyth'/210798, l='MpServer', x=397.72, y=66.62, z=422.42], EntityCreeper['Creeper'/250913, l='MpServer', x=444.50, y=26.00, z=444.50], EntityZombie['Zombie'/245091, l='MpServer', x=366.56, y=37.00, z=466.44], EntityCreeper['Creeper'/251199, l='MpServer', x=319.00, y=41.00, z=384.53], EntityOtherPlayerMP['LilAlbatross'/225101, l='MpServer', x=397.41, y=64.00, z=424.88]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.9.4
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 116833048 bytes (111 MB) / 819134464 bytes (781 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 64 mods loaded, 64 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.25.1207} [Forge Mod Loader] (forge-1.7.10-10.13.0.1207.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.0.1207} [Minecraft Forge] (forge-1.7.10-10.13.0.1207.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.2.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.2.15} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    simplyjetpackscore{1.0} [Simply Jetpacks Coremod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{1.7.10R3.0.0B3} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B3-26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalFoundation{1.7.10R1.0.0B1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B1-6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion{1.7.10R4.0.0B3} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B3-11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    appliedenergistics2{rv0-stable-10} [Applied Energistics 2] (appliedenergistics2-rv0-stable-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft{1.7.5} [BiblioCraft] (BiblioCraft[v1.7.5][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BigReactors{0.4.0rc2} [Big Reactors] (BigReactors-0.4.0rc2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.969-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry] (Blood Magic-v1.1.0(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    cookiecore{1.2.0} [Cookie Core] (cookiecore-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderIO{2.0_beta} [Ender IO] (enderio-2.0_beta.178.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.5} [Baubles] (Baubles-1.7.10-1.0.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraUtilities{1.1.0g} [Extra Utilities] (extrautilities-1.1.0g.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IronChest{6.0.49.733} [Iron Chest] (ironchest-1.7.10-6.0.49.733-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.3} [Waila] (Waila-1.5.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mantle{1.7.10-165.4bc3343} [Mantle] (Mantle_mc1.7.10_0.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded{1.7.10R2.8.0RC2} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC2} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC2} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC2} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC2} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC2} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC2} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft{4.2.0.0} [Thaumcraft] (Thaumcraft-1.7.10-4.2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Railcraft{9.2.2.0} [Railcraft] (Railcraft_1.7.10-9.2.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC2} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC2} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC2} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC2} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC2} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons{1.12.0.4} [NEI Addons] (neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|ExtraBees{1.12.0.4} [NEI Addons: Extra Bees] (neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|Forestry{1.12.0.4} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|CraftingTables{1.12.0.4} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|ExNihilo{1.12.0.4} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIPlugins{1.1.0.7-unofficial} [NEI Plugins Unofficial] (NEIPlugins-MC1.7.10-1.1.0.7-unofficial.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-223.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-430.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    harvestcraft{1.7.2d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    simplyjetpacks{1.1.0} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.7.10-1.6.0.build591} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TSteelworks{1.7.10-1.0.3} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TiCTooltips{1.1.9} [TiC Tooltips] (TiC-Tooltips-mc1.7.10-1.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IguanaTweaksTConstruct{1.7.10-2.0.1.DEV.84b0c6f} [Iguana Tweaks for Tinkers Construct] (IguanaTinkerTweaks-1.7.10-2.0.1B2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:ON, BC:OFF, MJ5:ON, MJ6:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, FMP:OFF
    Launched Version: 1.7.10-Forge10.13.0.1207
    LWJGL: 2.9.1
    OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-8.28.30, Intel Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by bonii-xx** [comment]
Update ITT.

**Comment by Daenyth** [comment]
Is the latest version on the releases tab here or elsewhere?

**Comment by bonii-xx** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks-2-0-2

Report back if it works with 2.0.2, please

**Comment by Daenyth** [comment]
Edit: It launches cleanly, failures were PEBCAK (got my client and server folders mixed up as I moved stuff around)

**Comment by bonii-xx** [comment]
I assume that means it works now. ;o

**Comment by Daenyth** [comment]
I haven't had the crash since upgrading (I only have it once before upgrading, but still).
